omardo/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="index"),
]

omardo/omardo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path("", include("main.urls")),
    path("", include("shortener.urls")),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

omardo/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("add/", views.add, name="add"),
]

omardo/shortener/urls.py
from django.urls import path

from . import views

app_name = "shortener"

urlpatterns = [
    path("_<key>/", views.get_redirect, name="redirect"),
    path("_/<key>/", views.get_redirect, name="redirect"),
]

omardo/main/models.py
from django.db import models

# Create your models here.

omardo/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def __str__(self):
        return self.question_text

    def votes_sum(self):
        return self.choice_set.aggregate(models.Sum("votes"))["votes__sum"]

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    # def votes_rate(self):
    #     total = self.question.votes_sum()
    #     return self.votes / total

    def __str__(self):
        return self.choice_text

omardo/shortener/models.py
import datetime
import string

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib import admin
from uuid import uuid4


class IntToBase:
    def __init__(self, number, base=10):
        self.number = number
        self.base = base

    def __iter__(self):
        self.remain = self.number
        return self

    def __next__(self):
        if self.remain <= 0:
            raise StopIteration
        x = self.remain % self.base
        self.remain = self.remain // self.base
        return x


class User(models.Model):
    key = models.UUIDField(default=uuid4, unique=True)
    email = models.EmailField("Correo Electrónico", max_length=254, null=True)
    email_verified = models.BooleanField(default=False)
    created = models.DateTimeField()

    def __str__(self):
        return self.email if self.email else self.key.hex


class ShortUrl(models.Model):
    def exists(key):
        return ShortUrl.objects.filter(key=key).exists()

    def generate_key():
        letters = string.digits + string.ascii_lowercase
        base = uuid4().hex

        for i in range(0, 24):
            key_int = int(base[i : i + 8], 16)
            key_test = "".join([letters[a] for a in IntToBase(key_int, len(letters))])

            if not ShortUrl.exists(key_test):
                break
        else:
            raise Exception("Please retry.")

        return key_test

    key = models.CharField(max_length=20, default=generate_key, unique=True)
    url = models.URLField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "{url_base}/_/{key}".format(url_base="https://omar.do", key=self.key)

omardo/polls/forms.py
from django.forms import ModelForm
from omardo.polls.models import Question


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ("question_text",)

omardo/main/views.py
from random import randint, randrange
from django.shortcuts import render


def get_random_data():
    emoji_list = "😀😁😂🤣😃😄😅😆😉😊😋😎😘🥰😗🤗🤩🤨😐😑😶😏😣😮😯😫😖😤😬🤠🙈"
    adverbio = ("cuando", "donde", "que")
    accion = (
        "saludo",
        "digo hola",
        "doy la bienvenida",
        "agradezco la visita",
        "informo cosas",
        "pongo un emoji aleatorio",
    )
    delayinterval = (1, 2, 3, 4)

    def rnd(list):
        return list[randrange(0, len(list))]

    return {
        "emoji": rnd(emoji_list),
        "adverbio": rnd(adverbio),
        "accion": rnd(accion),
        "delayinterval": rnd(delayinterval),
    }


# Create your views here.
def home(request):
    return render(
        request,
        "main/base.html",
        get_random_data(),
    )

omardo/polls/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView
from django.utils import timezone

# from omardo.polls.forms import QuestionForm
from .models import Question, Choice
from django_htmx.http import HttpResponseClientRedirect, retarget


# class AddView(CreateView):
#     model = Question
#     form_class = QuestionForm
#     template_name = "polls/add.html"


class IndexView(generic.ListView):
    template_name = "polls/list.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["header"] = kwargs["object"]
        return context

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context["header"] = kwargs["object"]
        context["subheader"] = "Respuestas"
        return context


def add(request: HttpRequest):
    template = "polls/notyet.html" if request.method == "POST" else "polls/add.html"
    return render(
        request,
        template,
        {},
    )


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "header": question,
                "error_message": "Debes seleccionar una opción.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

omardo/shortener/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from .models import ShortUrl


# Create your views here.
def get_redirect(request, key):
    url = get_object_or_404(ShortUrl, key=key)

    # return HttpResponseRedirect(url.url)
    return render(
        request,
        "shortener/redirect.html",
        {"output": "found: {url}".format(url=url.url)},
    )

omardo/main/templates/main/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">

	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'main/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'main/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'main/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'main/site.webmanifest' %}">

	{% tailwind_css %}
	<title>{% block title %}{{ title|default:"Sitio de Omar" }}{% endblock %}</title>
	<script src="{% static 'js/htmx.min.js' %}" defer ></script>
</head>
<body class="h-full" >
    {% block sidebar %}
        {% include "main/sidebar.html" %}
    {% endblock %}
	<div class="py-10">
		<header id="header" hx-swap-oob="true:#header">
			<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
				<h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">
					{{ header|default:CURRENT_APP.label }}
				</h1>
				{% if subheader %}
				<h2 class="text-xl leading-snug text-gray-700">{{subheader|title}}</h2>
				{% endif %}
			</div>
		</header>
		<main >
			<div id="content" hx-select="#content" hx-target="#content" hx-swap="outerHTML" hx-push-url="true" class="mx-auto mb-auto max-w-7xl px-6 lg:px-8 py-8">
			{% block content %}
			<p hx-get="/" hx-trigger="click, every {{ delayinterval }}m" >Aquí es {{ adverbio }} te {{ accion }}. {{emoji}}</p>
			{% endblock %}
			</div>
		</main>
        <footer>

            <div id="attributions" class="hidden">
                <a href="https://www.flaticon.com/icons" title="icons">Icons created by Freepik - Flaticon</a>
            </div>
        </footer>
	</div>
</body>
</html>

omardo/main/templates/main/sidebar.html
{% load static %}

<div id="sidebar" class="min-h-full">
	<nav class="border-b border-gray-200 bg-white">
	  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
		<div class="flex h-16 justify-between">
		  <div class="flex">
			<div class="flex flex-shrink-0 items-center">
			  <img class="block h-8 w-auto" src="{% static 'main/wrench.png' %}" alt="Logo">
			</div>
			<div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
			  {% for option in MENU_OPTIONS %}
                {% if option.active %}
                <a href="{% url option.url %}" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">
                {% else %}
                <a href="{% url option.url %}" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">
                {% endif %}
                {{ option.label }}
                </a>			    
              {% endfor %}
			</div>
		  </div>
		  
		</div>
	  </div>
  
	  <!-- Mobile menu, show/hide based on menu state. -->
	  <div class="sm:hidden" id="mobile-menu">
		<div class="space-y-1 pb-3 pt-2">
			  {% for option in MENU_OPTIONS %}
                {% if option.active %}
                <a href="{% url option.url %}" class="border-indigo-500 bg-indigo-50 text-indigo-700 block border-l-4 py-2 pl-3 pr-4 text-base font-medium" aria-current="page">
                {% else %}
                <a href="{% url option.url %}" class="border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium">
                {% endif %}
                {{ option.label }}
                </a>			    
              {% endfor %}
		</div>
	
	  </div>
	</nav>
  

omardo/polls/templates/polls/_base.html
{% extends "main/base.html" %}

omardo/polls/templates/polls/add.html
{% extends "polls/_base.html" %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<input type="text" placeholder="Question" />
	<button type="submit">Create</button>
</form>



{% endblock %}

omardo/polls/templates/polls/detail.html
{% extends "polls/_base.html" %}

{% block content %}

<form 
	hx-post="{% url 'polls:vote' question.id %}"
	action="{% url 'polls:vote' question.id %}" 
	method="post"
	
>
  {% csrf_token %}
  <p class="text-sm text-gray-500">Seleccione la opción más adecuada.</p> 
  <fieldset class="my-4">
    <legend class="sr-only">Opciones</legend>
    
	{% comment %} {% if error_message %} {% endcomment %}
    <p id="error-message"><strong>{{ error_message }}</strong></p>
    {% comment %} {% endif %}  {% endcomment %}
	<div class="space-y-4">
	{% for choice in question.choice_set.all %}
    <div class="flex items-center">
        <input id="choice{{ forloop.counter }}" name="choice" type="radio" class="h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-600" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}" class="ml-3 block text-sm font-medium leading-6 text-gray-900">
			{{ choice.choice_text }}
		</label>
    </div>
	{% endfor %}
	</div>
  </fieldset>
  
  <button 
  	type="submit" 
  	class="rounded-0 bg-cyan-800 px-2.5 mt-4 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-cyan-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600" 
  >Votar</button>
</form>

{% endblock %}

omardo/polls/templates/polls/error.html
{% extends "polls/_base.html" %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<input type="text" placeholder="Question" />
	<button type="submit">Create</button>
</form>
{% endblock %}

omardo/polls/templates/polls/list.html
{% extends "polls/_base.html" %}

{% load static %}

{% block content %}
<div>
<ul role="list" class="divide-y divide-gray-100">
{% for question in latest_question_list %}
<li class="relative flex justify-between py-5">
	<div class="flex gap-x-4 pr-6 sm:w-1/2 sm:flex-none">
		<img class="h-12 w-12 flex-none rounded-sm bg-gray-50" src="{% static "main/ballot.png" %}" alt="">
		<div class="min-w-0 flex-auto">
		  <p class="text-sm font-semibold leading-6 text-gray-900">
			<a 	href="#" hx-get="{% url 'polls:detail' question.id %}"
			>
			  <span class="absolute inset-x-0 -top-px bottom-0"></span>
			  {{ question.question_text }}
			</a>
		  </p>
		  <p class="mt-1 flex text-xs leading-5 text-gray-500">
			Creada el {{ question.pub_date }}
		  </p>
		</div>
	</div>
	<div class="flex items-center justify-between gap-x-4 sm:w-1/2 sm:flex-none">
		<div class="hidden sm:block">
			{% with question.votes_sum as votos %}
			<p class="text-sm leading-6 text-gray-900">{{ votos }} Voto{{ votos|pluralize}}</p>
			<p class="mt-1 text-xs leading-5 text-gray-500">{{ question.choice_set.count }} Opciones</p>
  
			{% endwith %}
		</div>
		<svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
		  <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
		</svg>
	</div>
</li>
{% endfor %}
<li class="relative flex justify-between py-5">
	<div class="flex gap-x-4 pr-6 sm:w-1/2 sm:flex-none">
		<img class="h-12 w-12 flex-none rounded-sm bg-gray-50" src="{% static "main/add.png" %}" alt="">
		<div class="min-w-0 flex-auto">
		  <p class="text-sm font-semibold leading-6 text-gray-900">
			<a href="#" hx-get="{% url 'polls:add' %}">
			  <span class="absolute inset-x-0 -top-px bottom-0"></span>
			  Añadir pregunta. 👀
			</a>
		  </p>
		  <p class="mt-1 flex text-xs leading-5 text-gray-500">
			Acá puedes añadir tus propias preguntas.
		  </p>
		</div>
	</div>
	<div class="flex items-center justify-end gap-x-4 sm:w-1/2 sm:flex-none">
		<svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
		  <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
		</svg>
	</div>

</li>
</ul>
</div>
{% endblock %}

omardo/polls/templates/polls/notyet.html
{% extends "polls/_base.html" %}

{% block content %}
<p>
	Esto aún no hace nada. pero gracias. 😘
</p>
{% endblock %}

omardo/polls/templates/polls/results.html
{% extends "polls/_base.html" %}

{% block content %}
<div class="flow-root">
	<div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8 border-black rounded-lg border">
		<table class="min-w-full divide-y divide-gray-300">
			<tbody class="divide-y divide-gray-200">	
				{% with question.votes_sum as total %}
				{% for choice in question.choice_set.all %}
				{% widthratio choice.votes total 100 as ratio %}
				<tr>
					<td class="w-2/3 whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
						{{ choice.choice_text }}
					</td>
					<td class="w-1/3 text-right whitespace-nowrap px-3 py-4 text-sm text-gray-700">
						<span>{{ ratio }}% </span>
						<meter class="md:w-2/3" max="100" value="{{ratio}}" >{{ choice.votes }} voto{{ choice.votes|pluralize }}</meter>
						<span>{{ choice.votes }} voto{{ choice.votes|pluralize }}</span>
					</td>
				</tr>
				{% endfor %}
				{% endwith %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}


	

omardo/shortener/templates/shortener/redirect.html
{% extends "main/base.html" %}

{% block content %}

<p>{{ output }}</p>


{% endblock %}